music_directory     "/home/rulio12/radio/music"
playlist_directory  "/home/rulio12/radio/playlists"
db_file             "/home/rulio12/radio/mpd.db"
log_file            "/home/rulio12/radio/mpd.log"
pid_file            "/home/rulio12/radio/mpd.pid"
state_file          "/home/rulio12/radio/mpd.state"
bind_to_address     "127.0.0.1"
port                "6600"

audio_output {
    type    "alsa"
    name    "Loopback"
    device  "hw:10,0"
    format  "44100:f:2"
    mixer_type "none"
}
